### ISSUE TITLE
KDE Daemon 4.22.0 (62f8f176) Segmentation fault

### ISSUE THREAD

**Issue by PF94** [fluxer/katana#34]
## Platform
OS: Linux 5.10.0-16-amd64 x86_64
Release: Debian GNU/Linux 11 (bullseye)
KDE: 4.22.0 (62f8f176)
Katie: 4.12.0
## Backtrace
Please, copy-paste it from the DrKonqi window

```
Application: KDE Daemon (kded4), signal: Segmentation fault
[KCrash Handler]
#6  0x00007f9e85e64a69 in ?? () from /lib/x86_64-linux-gnu/libKtGui.so.4.12.0
#7  0x00007f9e85912c7b in Katie::QCoreApplication::notifyInternal(Katie::QObject*, Katie::QEvent*) () from /lib/x86_64-linux-gnu/libKtCore.so.4.12.0
#8  0x00007f9e8592778a in Katie::QObjectPrivate::setParent_helper(Katie::QObject*) () from /lib/x86_64-linux-gnu/libKtCore.so.4.12.0
#9  0x00007f9e85927b9a in Katie::QObject::~QObject() () from /lib/x86_64-linux-gnu/libKtCore.so.4.12.0
#10 0x00007f9e858d95f9 in Katie::QProcess::~QProcess() () from /lib/x86_64-linux-gnu/libKtCore.so.4.12.0
#11 0x00007f9e858ff33e in ?? () from /lib/x86_64-linux-gnu/libKtCore.so.4.12.0
#12 0x00007f9e853104d7 in __run_exit_handlers (status=1, listp=0x7f9e85490718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#13 0x00007f9e8531067a in __GI_exit (status=<optimized out>) at exit.c:139
#14 0x00007f9e85eab456 in ?? () from /lib/x86_64-linux-gnu/libKtGui.so.4.12.0
#15 0x00007f9e86aff95f in _XIOError () from /lib/x86_64-linux-gnu/libX11.so.6
#16 0x00007f9e86afd025 in _XEventsQueued () from /lib/x86_64-linux-gnu/libX11.so.6
#17 0x00007f9e86aee8a0 in XEventsQueued () from /lib/x86_64-linux-gnu/libX11.so.6
#18 0x00007f9e85ed0d22 in ?? () from /lib/x86_64-linux-gnu/libKtGui.so.4.12.0
#19 0x00007f9e85911c54 in Katie::QEventLoop::processEvents(Katie::QFlags<Katie::QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libKtCore.so.4.12.0
#20 0x00007f9e85911f0e in Katie::QEventLoop::exec(Katie::QFlags<Katie::QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libKtCore.so.4.12.0
#21 0x00007f9e85916004 in Katie::QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libKtCore.so.4.12.0
#22 0x0000556c55ca6428 in main ()
[Inferior 1 (process 63532) detached]
```

not too sure if this is valid as the commit id matches my fork.

**Comment by fluxer** [comment]
I will look into the issue when I can, can't tell when that will be.

**Comment by fluxer** [comment]
This issue and issue #31 were happening very rarely and seem to be no longer occurring. If you want to test if they are make sure you have the latest and greatest source which is not hosted here.

Cheers!
